esphome:
  includes:
    - modules/xyeVars.h

substitutions:
  sensor_update_interval: 1s
  aux_update_interval: 15s

# This sensor updates once a second and just checks the Serial() buffer for anything to read
# A response is always 32 bytes of data, but only the first 30 are useful.
# If we happen to check the buffer midstream then this will skip that cycle and finish reading it on the next cycle.
# if nothing more comes in then it dumps the data
# Last, it checks if there was data waiting to be sent and sends that data after reading.
sensor:

  - platform: template
    name: "Inlet Air Temperature"
    unit_of_measurement: "°F"
    #unit_of_measurement: "°C"
    id: t1
    update_interval: $sensor_update_interval
    device_class: temperature
    lambda: |-
      return xyeVars.recData[T1_INDEX];


# this is the temperature of the refrigerant coming into the air handler from the compressor
# when it gets hot your compressor is heating, when it gets cold you are cooling.
# otherwise it should drift close to ambient or T1
  - platform: template
    name: "Coil A Temperature"
    unit_of_measurement: "°F"
    #unit_of_measurement: "°C"
    update_interval: $sensor_update_interval
    device_class: temperature
    lambda: |-
      return xyeVars.recData[T2A_INDEX];

  - platform: template
    name: "Coil B Temperature"
    unit_of_measurement: "°F"
    #unit_of_measurement: "°C"
    update_interval: $sensor_update_interval
    device_class: temperature
    lambda: |-
      return xyeVars.recData[T2B_INDEX];

# I don't think this is truly outside temperature. I think it's exhaust air temperature
# from the compressor outside which is ambient when it's not running.
  - platform: template
    name: "Outside Air Temperature"
    unit_of_measurement: "°F"
    #unit_of_measurement: "°C"
    update_interval: $sensor_update_interval
    device_class: temperature
    lambda: |-
      return xyeVars.recData[T3_INDEX];

# the 2 error code registers combined in one message. it's just the code number,
# you will need the service manual to decode them probably. I haven't tested any error
# codes yet. 
text_sensor:
  - platform: template
    name: "Error Codes"
    update_interval: $sensor_update_interval
    lambda: |-
      
      return {"E1: " + std::to_string(xyeVars.recData[REC_E1]) + " E2: " + std::to_string(xyeVars.recData[REC_E2])};

  - platform: template
    name: "Full data string"
    update_interval: $aux_update_interval
    lambda: |-
      std::ostringstream oss;
      oss << std::uppercase << std::hex << std::setfill('0');
      uint8_t i;
      for (i=0;i<(sizeof(xyeVars.recData) / sizeof(xyeVars.recData[0]));i++)
      {
        if (i>0)
        {
          oss << ' ';
        }
        oss << "0x";
        oss << std::setw(2) << static_cast<int>(xyeVars.recData[i]);
      }
      return {oss.str()};
      

select:
  - platform: template
    name: "Fan Mode"
    id: fanMode
    update_interval: $sensor_update_interval
    options:
      - 'low'
      - 'medium'
      - 'high'
      - 'auto'
      
    lambda: |-
      switch (xyeVars.fanBytes)
      {
        case 0x80: // 80 seems to be auto with fan off, ive also seen 81 (turbo in cool mode), 82, 84 (in cool mode). perhaps has to do with actual fan speed
          xyeVars.fan = "auto";
          break;
        case 0x01:
          xyeVars.fan = "high";
          break;
        case 0x02:
          xyeVars.fan = "medium";
          break;
        case 0x03:
          xyeVars.fan = "low";
          break;
        // case 0x81:
        //   xyeVars.fan = "turbo"; // only in cool mode
        //   break;
        default:
          ESP_LOGE("mideaXYE","xyeVars.fan defaulting to auto, invalid mode input: %02X",xyeVars.fanBytes);
          xyeVars.fan = "auto";
      }
      return xyeVars.fan;
    set_action: 
      - lambda: |-
          if (xyeVars.fan != x)
          {
            xyeVars.fan = x;
            ESP_LOGI("mideaXYE","change fan to: %s",x.str().c_str());
            if (xyeVars.fan == "high"){
              xyeVars.fanBytes = 0x01;
            } else if (xyeVars.fan == "auto"){
              xyeVars.fanBytes = 0x80;
            } else if (xyeVars.fan == "medium"){
              xyeVars.fanBytes = 0x02;
            } else if (xyeVars.fan == "low"){
              xyeVars.fanBytes = 0x03;
            } else {
              xyeVars.fanBytes = 0x80;
              ESP_LOGE("mideaXYE","Defaulting to auto, invalid fan input: %s",x.str().c_str());
            }
            ESP_LOGI("mideaXYE","selected %x, pressing button to send",xyeVars.fanBytes);
            xyeVars.newInput = true;
          }
    on_value:
      then:
        - script.execute:
            id: update_fan_mode_ui
            fan_mode: !lambda 'return x;'


  - platform: template
    id: opMode
    name: "Operating Mode"
    update_interval: $sensor_update_interval
    options:
      - 'off'
      - 'auto'
      - 'cool'
      - 'dry'
      - 'heat'
      - 'fan_only'
      # need to add switch case for updating the value based off xyeVars.opBytes
    lambda: |-
      switch (xyeVars.opBytes)
      {
        case 0x00:
          xyeVars.op = "off";
          break;
        case 0x91:
          xyeVars.op = "auto";
          break;
        case 0x88:
          xyeVars.op = "cool";
          break;
        case 0x82:
          xyeVars.op = "dry";
          break;
        case 0x84:
          xyeVars.op = "heat";
          break;
        case 0x81:
          xyeVars.op = "fan_only";
          break;
        default:
          ESP_LOGE("mideaXYE","xyeVars.op defaulting to off, invalid mode input: %02X",xyeVars.opBytes);
          xyeVars.op = "off";
      }
      return xyeVars.op;
    set_action:
      - lambda: |-
          if (xyeVars.op != x)
          {
            xyeVars.op = x;
            if (xyeVars.op == "off"){
              xyeVars.opBytes = 0x00;
            } else if (xyeVars.op == "auto"){
              xyeVars.opBytes = 0x91;
            } else if (xyeVars.op == "cool"){
              xyeVars.opBytes = 0x88;
            } else if (xyeVars.op == "dry"){
              xyeVars.opBytes = 0x82;
            } else if (xyeVars.op == "heat"){
              xyeVars.opBytes = 0x84;
            } else if (xyeVars.op == "fan_only"){
              xyeVars.opBytes = 0x81;
            } else {
              xyeVars.opBytes = 0x00;
              ESP_LOGE("mideaXYE","Defaulting to off, invalid mode input: %s",x.str().c_str());
            }
            ESP_LOGI("mideaXYE","selected %x for mode, setting send flag",xyeVars.opBytes);
            xyeVars.newInput = true;
          }
    on_value:
      then:
        - script.execute:
            id: update_hvac_mode_ui
            mode: !lambda 'return x;'

# this is the internal setpoint for the hvac controller
# we will adjust this one as needed to get the behavior that we want
# we will hide this one from the UI; it's an internal one only
number:
  - platform: template
    name: "Internal Set Point"
    id: internal_set_point
    internal: true # dont want anyone changing this directly, it's just for internal use
    step: 1
    mode: box
    min_value: 0
    max_value: 100
    unit_of_measurement: "°F"
    #unit_of_measurement: "°C"
    device_class: temperature
    update_interval: $sensor_update_interval
    lambda: |-
      return xyeVars.setTemp;
    set_action:
      - then:
        - lambda: |-
            xyeVars.setTemp = x;
            xyeVars.newInput = true;

# FIXME: weird stuff happens when i activate this
# climate:
#   - platform: thermostat
#     name: "Midea Thermostat"
#     id: tstat
#     sensor: average_house_temperature

#     visual:
#       temperature_step:
#         target_temperature: 1
#         current_temperature: 1

#     # this block is placeholder since we aren't actually controlling when the AC runs
#     min_cooling_off_time: 1s
#     min_cooling_run_time: 1s
#     min_heating_off_time: 1s
#     min_heating_run_time: 1s
#     min_fanning_off_time: 1s
#     min_fanning_run_time: 1s
#     min_fan_mode_switching_time: 1s
#     min_idle_time: 1s
#     cool_action:
#       - delay: 1ms
#     heat_action:
#       - delay: 1ms
#     idle_action:
#       - delay: 1ms
#     dry_action:
#       - delay: 1ms
#     fan_only_action:
#       - delay: 1ms

#     # set target temperature on change
#     # sets the UI setpoint
#     target_temperature_change_action:
#       - number.set: 
#           id: visible_setpoint_value
#           value: !lambda "return id(tstat).target_temperature;"

#     # mode changes for operation and fan settings
#     cool_mode:
#       - select.set: 
#           id: opMode
#           option: "cool"
#     heat_mode:
#       - select.set: 
#           id: opMode
#           option: "heat"
#     off_mode:
#       - select.set: 
#           id: opMode
#           option: "off"
#     dry_mode:
#       - select.set:
#           id: opMode
#           option: "dry"
#     fan_only_mode:
#       - select.set:
#           id: opMode
#           option: "fan_only"
#     auto_mode:
#       - select.set:
#           id: opMode
#           option: "auto"
#     fan_mode_auto_action:
#       - select.set: 
#           id: fanMode
#           option: "auto"
#     fan_mode_low_action:
#       - select.set: 
#           id: fanMode
#           option: "low"
#     fan_mode_medium_action:
#       - select.set: 
#           id: fanMode
#           option: "medium"
#     fan_mode_high_action:
#       - select.set: 
#           id: fanMode
#           option: "high"
