# this module contains only the UART configuration for the mideaXYE module. It is included in the main mideaXYE.yaml file.
# This allows us to run the SDL2 simulation without having the UART stuff
# these scripts and sensors are used to send and receive data from the air handler. 
# The send_command script is called when a new input is received from the UI, and it constructs the command to send to the air handler. 
# The wait_send script is called when we have data that was blocked by incoming data, and it sends that data after the incoming data has been processed. 
# The updater sensor checks for incoming data and processes it by writing to xyeVars.
# The querier sensor sends a query package to the air handler every 15 seconds.

# add this to replace the mySerial thing from arduino 
uart:
  id: midea_uart
  tx_pin: GPIO44 # This is the correct pin for the waveshare device
  rx_pin: GPIO43 # This is the correct pin for the waveshare device
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: NONE

script:
# this script sends data that was blocked by incoming data
  - id: wait_send
    then:
    - lambda: |-
        id(midea_uart).write_array(xyeVars.waitSendData,16);
        xyeVars.waitingForResponse = true;
        xyeVars.waitingToSend = false;
        xyeVars.commandSent = true;

# this will construct the command to send to the air handler, called by the input sensors
# when required.  It tries to not send if we're in the middle of receiving.
  - id: send_command
    then:
    - lambda: |-
        if (!xyeVars.waitingForResponse)
        {
          uint8_t resp;
          xyeVars.sendData[SEND_MODE] = xyeVars.opBytes;
          xyeVars.sendData[SEND_FAN] = xyeVars.fanBytes;
          xyeVars.sendData[SEND_TEMP] = xyeVars.setTemp;
          ESP_LOGD("mideaXYE","Getting ready to send: op %02X fan %02X temp %02X",xyeVars.opBytes,xyeVars.fanBytes,xyeVars.setTemp);
          uint8_t i=0;
          uint32_t crc=0;
          int len=16;
          for(i=0;i<len;i++)
          { 
            if(i!=SEND_CRC)
            {
              crc+=xyeVars.sendData[i];
            }
          }
          ESP_LOGD("mideaXYE","sum of values for CRC calc is %i",crc);
          xyeVars.sendData[SEND_CRC] = 0xFF - (crc&0xFF);
          ESP_LOGD("mideaXYE","calculated CRC is %x",crc);
          resp = id(midea_uart).available();
          if (resp==0) 
          {
            id(midea_uart).write_array(xyeVars.sendData, SEND_LEN);
            ESP_LOGD("mideaXYE","sent command");
            xyeVars.waitingForResponse = true;
            xyeVars.commandSent = true;
          } else {
            ESP_LOGD("mideaXYE","had to wait to send, response was available");
            std::memcpy(xyeVars.waitSendData, xyeVars.sendData, 16);
            xyeVars.waitingToSend = true;
          }
          xyeVars.newInput = false;
          xyeVars.sendTimeCount = 0;
        }

sensor:
  - platform: template
    name: "updater"
    id: updater
    internal: true
    update_interval: $sensor_update_interval
    lambda: |-
      uint8_t i,resp;
      xyeVars.doneReading = false;
      ESP_LOGD("mideaXYE","checking for incoming serial data");
      resp = id(midea_uart).available();
      if (resp>0)
      {
        ESP_LOGD("mideaXYE","there are %i bytes of data waiting",resp);
        if (resp == 32)
        {
          ESP_LOGD("mideaXYE","32 bytes of data found, reading data...");
          for (i=0; i<resp; i++)
          {
            if (i<30)
            {
              id(midea_uart).read_byte(&xyeVars.recData[i]);
            } else
            {
              uint8_t dummy;
              id(midea_uart).read_byte(&dummy);
            }
          }
          ESP_LOGD("mideaXYE","done reading, examining data");
          xyeVars.doneReading = true;
          xyeVars.waitingForResponse = false;
          xyeVars.prevResp = 0;
        } else if (xyeVars.prevResp == resp) 
        {
          // it's been 2 update cycles with no change in length of data, this is leftover data. dump it.
          for (i=0;i<resp;i++)
          {
            uint8_t dummy;
            id(midea_uart).read_byte(&dummy);
          }
          ESP_LOGW("mideaXYE","dumped some data: %i",resp);
          xyeVars.waitingForResponse = false;
          xyeVars.prevResp = 0;
          xyeVars.doneReading = true;
        } else 
        {
              // might have caught in middle of stream
              ESP_LOGW("mideaXYE","got small response, wait for more. size was %i", resp);
              xyeVars.prevResp = resp;
        }
      }
      if (xyeVars.waitingForResponse)
      {
        if (xyeVars.waitCount > 2){
          ESP_LOGW("mideaXYE","waited 3 cycles for a response, giving up");
          xyeVars.waitingForResponse = false;
          xyeVars.waitCount = 0;
          xyeVars.doneReading = true;
        } else {
          xyeVars.waitCount ++;
        }
       
      }

      if (xyeVars.doneReading) 
      {
        if (!xyeVars.commandSent && !xyeVars.newInput)
        {
          bool theyMatch = true;
          for (i=0;i<6;++i)
          {
            if (i != 1) {
              if (xyeVars.recData[i]!=xyeVars.checkData[i])
              {
                theyMatch = false;
              }
            }
          }
          if (theyMatch)
          {
            xyeVars.fanBytes = xyeVars.recData[REC_FAN];
            xyeVars.opBytes = xyeVars.recData[REC_MODE];
            xyeVars.setTemp = xyeVars.recData[REC_TEMP];
            ESP_LOGD("mideaXYE","Got these updated values: op %02X fan %02X temp %02X",xyeVars.opBytes,xyeVars.fanBytes,xyeVars.setTemp);
          } else 
          {
            ESP_LOGW("mideaXYE","First 6 bytes of incoming data were bad, not using values");
          }
        } else
        {
          xyeVars.commandSent = false;
          ESP_LOGI("mideaXYE","dumping first received data after command sent OR had new input waiting to send");
        }
        if (xyeVars.waitingToSend) 
        {
          ESP_LOGI("mideaXYE","finished reading, had data waiting to write. now writing...");
          id(wait_send).execute();
        }
        
      }

      // now check if we need to send new data
      if (xyeVars.newInput)
      {
        // give at least 5 cycles to accumulate changes (multiple presses of the temperature button for example)
        if (xyeVars.sendTimeCount > 4) {
          xyeVars.sendTimeCount = 0;
          id(send_command).execute();
        } else 
        {
          xyeVars.sendTimeCount += 1;
        }
      }
      return 0;


# this sensor updates every 15 seconds. when it updates, it sends a query package to the
# air handler. The query package is the always the same, xyeVars.queryData.
  - platform: template
    name: "querier"
    id: querier
    internal: true
    update_interval: $aux_update_interval
    lambda: |-
      ESP_LOGD("mideaXYE","query check. newInput: %s  waitingForResponse:  %s",xyeVars.newInput ? "true" : "false", xyeVars.waitingForResponse ? "true" : "false");
      if (!xyeVars.newInput && !xyeVars.waitingForResponse)
      {
        uint8_t resp=id(midea_uart).available();
        ESP_LOGD("mideaXYE","going to send a query package...");
        if (!(xyeVars.waitingToSend || (resp != 0)))
        {
          id(midea_uart).write_array(xyeVars.queryData,16);
          ESP_LOGD("mideaXYE","sent query package, waiting for response...");
          xyeVars.waitingForResponse = true;
        } else 
        {
          ESP_LOGD("mideaXYE","waiting to send/receive prevented sending query package");
        }
      }
      return 0;