esphome:
  includes:
    - modules/xyeVars.h

substitutions:
  sensor_update_interval: 1s
  aux_update_interval: 15s

interval:
  # update sensors
  - interval: $sensor_update_interval
    then:
      - lambda: |-
          // publish sensor states only if recdata is different (i.e. only on new values)
          // publishing state skips the set_action, but not on_value
          if (id(t1).state != xyeVars.recData[T1_INDEX]) {
            ESP_LOGI("mideaXYE", "t1 state has changed from %f to %u", id(t1).state, xyeVars.recData[T1_INDEX]);
            id(t1).publish_state(xyeVars.recData[T1_INDEX]);
          }

          if (id(t2a).state != xyeVars.recData[T2A_INDEX]) {
            ESP_LOGI("mideaXYE", "t2a state has changed from %f to %u", id(t2a).state, xyeVars.recData[T2A_INDEX]);
            id(t2a).publish_state(xyeVars.recData[T2A_INDEX]);
          }

          if (id(t2b).state != xyeVars.recData[T2B_INDEX]) {
            ESP_LOGI("mideaXYE", "t2b state has changed from %f to %u", id(t2b).state, xyeVars.recData[T2B_INDEX]);
            id(t2b).publish_state(xyeVars.recData[T2B_INDEX]);
          }

          if (id(t3).state != xyeVars.recData[T3_INDEX]) {
            ESP_LOGI("mideaXYE", "t3 state has changed from %f to %u", id(t3).state, xyeVars.recData[T3_INDEX]);
            id(t3).publish_state(xyeVars.recData[T3_INDEX]);
          }

          if (id(fanBytes).state != xyeVars.recData[REC_FAN]) {
            ESP_LOGI("mideaXYE", "fanBytes state has changed from %f to %u", id(fanBytes).state, xyeVars.recData[REC_FAN]);
            id(fanBytes).publish_state(xyeVars.recData[REC_FAN]);

            // update the fanmode and fanstatus text sensors
            id(fanStatus).update();
            id(fanMode).update();
          }

          if (id(modeBytes).state != xyeVars.recData[REC_MODE]) {
            ESP_LOGI("mideaXYE", "modeBytes state has changed from %f to %u", id(modeBytes).state, xyeVars.recData[REC_MODE]);
            id(modeBytes).publish_state(xyeVars.recData[REC_MODE]);

            // update the mode select
            id(opMode).update();
          }

# FIXME: the 60s update interval slows down my computer; try to find why, if can fix, otherwise never update and rely on hooks
sensor:
# This sensor updates once a second and just checks the Serial() buffer for anything to read
# A response is always 32 bytes of data, but only the first 30 are useful.
# If we happen to check the buffer midstream then this will skip that cycle and finish reading it on the next cycle.
# if nothing more comes in then it dumps the data
# Last, it checks if there was data waiting to be sent and sends that data after reading.
  - platform: template
    name: "Inlet Air Temperature"
    unit_of_measurement: "°F"
    id: t1
    device_class: temperature
    on_value: 
      then:
        - logger.log:
            format: "t1 emperature changed to %.1f, executing update_setpoints script"
            args: x
            level: DEBUG
            tag: "mideaXYE"
        - script.execute:
            id: update_setpoints
            visible_setpoint: !lambda 'return id(visible_setpoint_value).state;'
        - component.update: hvac_status


# this is the temperature of the refrigerant coming into the air handler from the compressor
# when it gets hot your compressor is heating, when it gets cold you are cooling.
# otherwise it should drift close to ambient or T1
  - platform: template
    name: "Coil A Temperature"
    id: t2a
    unit_of_measurement: "°F"
    device_class: temperature
    on_value:
      - component.update: hvac_status

  - platform: template
    name: "Coil B Temperature"
    id: t2b
    unit_of_measurement: "°F"
    device_class: temperature

# I don't think this is truly outside temperature. I think it's exhaust air temperature
# from the compressor outside which is ambient when it's not running.
  - platform: template
    name: "Outside Air Temperature"
    id: t3
    unit_of_measurement: "°F"
    device_class: temperature
    on_value:
      - component.update: hvac_status

# internal helper sensor to track the state of the fan bytes
  - platform: template
    name: Fan Bytes Sensor
    id: fanBytes
    internal: True

# internal helper sensor to track the state of the opmode bytes
  - platform: template
    name: OpMode Bytes Sensor
    id: modeBytes
    internal: True


text_sensor:
# logic to determine what the hvac status is: cooling/heating/diffusing
  - platform: template
    name: HVAC Status
    id: hvac_status
    lambda: |-
      // this script looks at the fan modes and coil temps to determine if the unit 
      // is actively heating, cooling, or diffusing
      // if the t2a temp is > t1 by at least 10 degrees, then we are heating
      // if t2a temp is < t1 by at least 10 degrees, then we are cooling
      // if t2a temp is close to t1 temp, and fan status is not zero then we are diffusing
      // get the variables
      uint8_t t1_temp = xyeVars.recData[T1_INDEX];
      uint8_t t2a_temp = xyeVars.recData[T2A_INDEX];
      std::string fan_status = id(fanStatus).state;
      std::string hvac_mode = id(opMode).current_option();
      bool fan_is_on = fan_status != "off";

      std::vector<std::string> cooling_modes = {"cool", "dry", "auto"};
      std::vector<std::string> heating_modes = {"heat", "auto"};

      int temp_threashold = 10;
      std::string result;

      if ((t2a_temp - t1_temp) > temp_threashold) {
        result = "Heating";
      } else if ((t2a_temp - t1_temp) < -temp_threashold) {
        result = "Cooling";
      } else if (fan_is_on) {
        result = "Diffusing";
      } else result = "";

      // check that the status and mode match up
      if (result == "Heating" && (std::find(heating_modes.begin(), heating_modes.end(), hvac_mode) == heating_modes.end())) {
        ESP_LOGE("mideaXYE", "t1_temp is %u, t2_temp is %u, which means the hvac status should be %s, but the hvac mode is %s which does not make sense! Setting hvac_status to Diffusing.", t1_temp, t2a_temp, result.c_str(), hvac_mode.c_str());
        result = "Diffusing";
      } else if (result == "Cooling" && (std::find(cooling_modes.begin(), cooling_modes.end(), hvac_mode) == cooling_modes.end())) {
        ESP_LOGE("mideaXYE", "t1_temp is %u, t2_temp is %u, which means the hvac status should be %s, but the hvac mode is %s which does not make sense! Setting hvac_status to Diffusing.", t1_temp, t2a_temp, result.c_str(), hvac_mode.c_str());
        result = "Diffusing";
      } else if (result == "Diffusing" && hvac_mode == "off") {
        ESP_LOGE("mideaXYE", "t1_temp is %u, t2_temp is %u, fan_status is %s, which means the hvac status should be %s, but the hvac mode is %s which does not make sense! Setting hvac_status to err.", t1_temp, t2a_temp, fan_status.c_str(), result.c_str(), hvac_mode.c_str());
        result = "err";
      }
      
      // final check if the fan is actually on
      if ((result == "Heating" || result == "Cooling" || result == "Diffusing") && !fan_is_on) {
        ESP_LOGE("mideaXYE", "t1_temp is %u, t2_temp is %u, which means the hvac status should be %s, but the fan is %s which we interpret as OFF! Setting hvac_status to err.", t1_temp, t2a_temp, result.c_str(), fan_status.c_str());
        result = "err";
      }

      ESP_LOGD("mideaXYE", "t1_temp is %u, t2_temp is %u, fan_status is %s, hvac_mode is %s, and so the hvac status is %s", t1_temp, t2a_temp, fan_status.c_str(), hvac_mode.c_str(), result.c_str());
      return result;
    on_value:
      - script.execute: update_hvac_status_ui
# the 2 error code registers combined in one message. it's just the code number,
# you will need the service manual to decode them probably. I haven't tested any error
# codes yet. 
  - platform: template
    name: "Error Codes"
    update_interval: $sensor_update_interval
    lambda: |-
      return {"E1: " + std::to_string(xyeVars.recData[REC_E1]) + " E2: " + std::to_string(xyeVars.recData[REC_E2])};

# this sensor tells us what the current fan speed is
  - platform: template
    name: Fan Status
    id: fanStatus
    lambda: |-
      // update the fan status
      // define the options
      std::vector<uint8_t> off_status = {0x00, 0x80};
      std::vector<uint8_t> low_status = {0x04, 0x84};
      std::vector<uint8_t> med_status = {0x02, 0x82};
      std::vector<uint8_t> high_status = {0x01, 0x81};

      // cast fanBytes back to uint8
      uint8_t fanBytes = xyeVars.recData[REC_FAN];

      // assert fanbytes == xyeVars.fanBytes
      if (fanBytes != xyeVars.fanBytes) {
        ESP_LOGE("mideaXYE", "xyeVars.recData[REC_FAN] (0x%02x) != xyeVars.fanBytes (0x%02x)!", fanBytes, xyeVars.fanBytes);
        return "err";
      } else {
        // set the fanStatus
        // std::find returns numbers.end() if the value isn't found
        if (std::find(off_status.begin(), off_status.end(), fanBytes) != off_status.end()) {
            ESP_LOGD("mideaXYE", "fanBytes is 0x%02x and means OFF", fanBytes);
            return "off";
        } else if (std::find(low_status.begin(), low_status.end(), fanBytes) != low_status.end()) {
            ESP_LOGD("mideaXYE", "fanBytes is 0x%02x and means LOW", fanBytes);
             return "low";
        } else if (std::find(med_status.begin(), med_status.end(), fanBytes) != med_status.end()) {
            ESP_LOGD("mideaXYE", "fanBytes is 0x%02x and means MED", fanBytes);
            return "med";
        } else if (std::find(high_status.begin(), high_status.end(), fanBytes) != high_status.end()) {
            ESP_LOGD("mideaXYE", "fanBytes is 0x%02x and means HIGH", fanBytes);
            return "high";
        } else {
          ESP_LOGE("mideaXYE", "fanBytes is 0x%02x, and could not determine what this means!", fanBytes);
          return "err";
        }
      }
    on_value:
      - component.update: hvac_status
      

select:
  - platform: template
    name: "Fan Mode"
    id: fanMode
    options:
      - 'low'
      - 'medium'
      - 'high'
      - 'auto'
      
    lambda: |-
      std::vector<uint8_t> auto_modes = {0x80, 0x81, 0x82, 0x84};

      if (xyeVars.fanBytes == 0x01) {
        ESP_LOGD("mideaXYE","xyeVars.fanBytes is 0x%02X, xyeVars.fanMode set to high",xyeVars.fanBytes);
        xyeVars.fanMode = "high";
      } else if (xyeVars.fanBytes == 0x02) {
        ESP_LOGD("mideaXYE","xyeVars.fanBytes is 0x%02X, xyeVars.fanMode set to medium",xyeVars.fanBytes);
        xyeVars.fanMode = "medium";
      } else if (xyeVars.fanBytes == 0x04) {
        ESP_LOGD("mideaXYE","xyeVars.fanBytes is 0x%02X, xyeVars.fanMode set to low",xyeVars.fanBytes);
        xyeVars.fanMode = "low";
      } else if (std::find(auto_modes.begin(), auto_modes.end(), xyeVars.fanBytes) != auto_modes.end()) {
        ESP_LOGD("mideaXYE","xyeVars.fanBytes is 0x%02X, xyeVars.fanMode set to auto",xyeVars.fanBytes);
        xyeVars.fanMode = "auto";
      } else if (xyeVars.fanBytes == 0x00) {
        ESP_LOGD("mideaXYE","xyeVars.fanBytes is 0x%02X, not changing xyeVars.fanMode. it is still %s",xyeVars.fanBytes, id(fanMode).current_option().c_str());
      } else {
        ESP_LOGE("mideaXYE","xyeVars.fanMode defaulting to auto, invalid mode input: %02X",xyeVars.fanBytes);
        xyeVars.fanMode = "auto";
      }
      return xyeVars.fanMode;
    set_action: 
      - lambda: |-
          if (xyeVars.fanMode != x)
          {
            xyeVars.fanMode = x;
            ESP_LOGI("mideaXYE","change fan to: %s",x.str().c_str());
            if (xyeVars.fanMode == "high"){
              xyeVars.fanBytes = 0x01;
            } else if (xyeVars.fanMode == "auto"){
              xyeVars.fanBytes = 0x80;
            } else if (xyeVars.fanMode == "medium"){
              xyeVars.fanBytes = 0x02;
            } else if (xyeVars.fanMode == "low"){
              xyeVars.fanBytes = 0x04;
            } else {
              xyeVars.fanBytes = 0x80;
              ESP_LOGE("mideaXYE","Defaulting to auto, invalid fan input: %s",x.str().c_str());
            }
            ESP_LOGI("mideaXYE","selected %x, pressing button to send",xyeVars.fanBytes);
            xyeVars.newInput = true;
            id(fanMode).publish_state(x);
          }
    on_value:
      then:
        - script.execute:
            id: update_fan_mode_ui
            fan_mode: !lambda 'return x;'


  - platform: template
    id: opMode
    name: "Operating Mode"
    options:
      - 'off'
      - 'auto'
      - 'cool'
      - 'dry'
      - 'heat'
      - 'fan_only'
      # need to add switch case for updating the value based off xyeVars.opBytes
    lambda: |-
      ESP_LOGD("mideaXYE", "Entering opMode lambda. xyeVars.opBytes is 0x%02x", xyeVars.opBytes);
      switch (xyeVars.opBytes)
      {
        case 0x00:
          xyeVars.op = "off";
          break;
        case 0x91:
          xyeVars.op = "auto";
          break;
        case 0x88:
          xyeVars.op = "cool";
          break;
        case 0x82:
          xyeVars.op = "dry";
          break;
        case 0x84:
          xyeVars.op = "heat";
          break;
        case 0x81:
          xyeVars.op = "fan_only";
          break;
        default:
          ESP_LOGE("mideaXYE","xyeVars.op defaulting to off, invalid mode input: %02X",xyeVars.opBytes);
          xyeVars.op = "off";
      }
      ESP_LOGD("mideaXYE", "xyeVars.op is %s", xyeVars.op.c_str());
      return xyeVars.op;
    set_action:
      - lambda: |-
          if (xyeVars.op != x)
          {
            xyeVars.op = x;
            if (xyeVars.op == "off"){
              xyeVars.opBytes = 0x00;
            } else if (xyeVars.op == "auto"){
              xyeVars.opBytes = 0x91;
            } else if (xyeVars.op == "cool"){
              xyeVars.opBytes = 0x88;
            } else if (xyeVars.op == "dry"){
              xyeVars.opBytes = 0x82;
            } else if (xyeVars.op == "heat"){
              xyeVars.opBytes = 0x84;
            } else if (xyeVars.op == "fan_only"){
              xyeVars.opBytes = 0x81;
            } else {
              xyeVars.opBytes = 0x00;
              ESP_LOGE("mideaXYE","Defaulting to off, invalid mode input: %s",x.str().c_str());
            }
            ESP_LOGI("mideaXYE","selected %x for mode, setting send flag",xyeVars.opBytes);
            xyeVars.newInput = true;
            id(opMode).publish_state(x);
          }
    on_value:
      then:
        - script.execute:
            id: update_hvac_mode_ui
            mode: !lambda 'return x;'

# this is the internal setpoint for the hvac controller
# we will adjust this one as needed to get the behavior that we want
# we will hide this one from the UI; it's an internal one only
number:
  - platform: template
    name: "Internal Set Point"
    id: internal_set_point
    internal: true # dont want anyone changing this directly, it's just for internal use
    step: 1
    mode: box
    min_value: 0
    max_value: 100
    unit_of_measurement: "°F"
    #unit_of_measurement: "°C"
    device_class: temperature
    update_interval: $sensor_update_interval
    lambda: |-
      return xyeVars.setTemp;
    set_action:
      - then:
        - lambda: |-
            xyeVars.setTemp = x;
            xyeVars.newInput = true;

# FIXME: weird stuff happens when i activate this
# climate:
#   - platform: thermostat
#     name: "Midea Thermostat"
#     id: tstat
#     sensor: average_house_temperature

#     visual:
#       temperature_step:
#         target_temperature: 1
#         current_temperature: 1

#     # this block is placeholder since we aren't actually controlling when the AC runs
#     min_cooling_off_time: 1s
#     min_cooling_run_time: 1s
#     min_heating_off_time: 1s
#     min_heating_run_time: 1s
#     min_fanning_off_time: 1s
#     min_fanning_run_time: 1s
#     min_fan_mode_switching_time: 1s
#     min_idle_time: 1s
#     cool_action:
#       - delay: 1ms
#     heat_action:
#       - delay: 1ms
#     idle_action:
#       - delay: 1ms
#     dry_action:
#       - delay: 1ms
#     fan_only_action:
#       - delay: 1ms

#     # set target temperature on change
#     # sets the UI setpoint
#     target_temperature_change_action:
#       - number.set: 
#           id: visible_setpoint_value
#           value: !lambda "return id(tstat).target_temperature;"

#     # mode changes for operation and fan settings
#     cool_mode:
#       - select.set: 
#           id: opMode
#           option: "cool"
#     heat_mode:
#       - select.set: 
#           id: opMode
#           option: "heat"
#     off_mode:
#       - select.set: 
#           id: opMode
#           option: "off"
#     dry_mode:
#       - select.set:
#           id: opMode
#           option: "dry"
#     fan_only_mode:
#       - select.set:
#           id: opMode
#           option: "fan_only"
#     auto_mode:
#       - select.set:
#           id: opMode
#           option: "auto"
#     fan_mode_auto_action:
#       - select.set: 
#           id: fanMode
#           option: "auto"
#     fan_mode_low_action:
#       - select.set: 
#           id: fanMode
#           option: "low"
#     fan_mode_medium_action:
#       - select.set: 
#           id: fanMode
#           option: "medium"
#     fan_mode_high_action:
#       - select.set: 
#           id: fanMode
#           option: "high"
