esphome:
  name: hvac-thermostat-sim
  friendly_name: Simulated HVAC Thermostat

logger:
  level: DEBUG

packages:
  main_ui: !include modules/thermostat_ui.yaml
  time_config: !include modules/time_host.yaml
  xye_config: !include modules/mideaXYE.yaml

host:

# network and api sections so simulator can talk to hass
network:
  enable_ipv6: false

api:
  encryption:
    key: !secret encryption_key

display:
  - platform: sdl
    id: my_display
    dimensions:
      width: 800
      height: 480

touchscreen:
  - platform: sdl
    id: my_touch
    display: my_display

number: 
# these are for simulating new data from the midea unit
  - platform: template
    name: "Fan Bytes"
    id: fanBytes
    step: 1
    mode: box
    min_value: 0
    max_value: 255
    update_interval: $sensor_update_interval
    lambda: |-
      return xyeVars.fanBytes;
    set_action:
      - lambda: |-
          xyeVars.fanBytes = x;

  - platform: template
    name: "Op Bytes"
    id: opBytes
    step: 1
    mode: box
    min_value: 0
    max_value: 255
    update_interval: $sensor_update_interval
    lambda: |-
      return xyeVars.opBytes;
    set_action:
      - lambda: |-
          xyeVars.opBytes = x;

  - platform: template
    name: "Set Temp"
    id: setTemp
    step: 1
    mode: box
    min_value: 0
    max_value: 100
    update_interval: $sensor_update_interval
    lambda: |-
      return xyeVars.setTemp;
    set_action:
      - lambda: |-
          xyeVars.setTemp = x;