esphome:
  name: hvac-thermostat-sim
  friendly_name: Simulated HVAC Thermostat

logger:
  level: DEBUG

packages:
  main: !include thermostat_ui.yaml
  time_config: !include time_host.yaml

host:

display:
  - platform: sdl
    id: my_display
    dimensions:
      width: 800
      height: 480

touchscreen:
  - platform: sdl
    id: my_touch
    display: my_display