# https://community.home-assistant.io/t/esp32-s3-4-3inch-capacitive-touch-display-from-waveshare/658279/78

esphome:
  name: hvac-thermostat
  friendly_name: HVAC Thermostat

logger:
  level: DEBUG

packages:
  hardware_config: !include hardware_config.yaml
  thermostat_ui: !include thermostat_ui.yaml


time:
  # pull in automation from thermostat_ui.yaml to set the time on the ESP32-S3
  - platform: sntp
    timezone: "America/Los_Angeles"
    id: sntp_time