# https://community.home-assistant.io/t/esp32-s3-4-3inch-capacitive-touch-display-from-waveshare/658279/78

esphome:
  name: hvac-thermostat
  friendly_name: HVAC Thermostat

logger:
  level: DEBUG

packages:
  hardware_config: !include modules/hardware_config.yaml
  thermostat_ui: !include modules/thermostat_ui.yaml
  time_config: !include modules/time_sntp.yaml
  xye_config: !include modules/mideaXYE.yaml
  xye_uart: !include modules/mideaXYE_uart.yaml
  xye_all_sensors: !include modules/mideaXYE_all_recbytes.yaml