# https://community.home-assistant.io/t/esp32-s3-4-3inch-capacitive-touch-display-from-waveshare/658279/78

esphome:
  name: hvac-thermostat
  friendly_name: HVAC Thermostat

logger:
  level: DEBUG

packages:
  hardware_config: !include hardware_config.yaml
  thermostat_ui: !include thermostat_ui.yaml
  time_config: !include time_sntp.yaml